name: Optimize images

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run image optimizer
        run: pnpm run images:optimize

      - name: Commit optimized images
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/optimized || true
          if git diff --staged --quiet; then
            echo "No optimized images to commit"
          else
            git commit -m "chore: add optimized images (generated by CI)" || true
            git push origin HEAD:main || echo "Push failed — possibly due to branch protection"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
